feat: add Vault installation and reset functions with Helm support

diff --git a/install_k8s/gok b/install_k8s/gok
--- a/install_k8s/gok
+++ b/install_k8s/gok
@@ -1838,6 +1838,61 @@ opensearchSecret(){
     --from-literal=OPENSEARCH_INITIAL_ADMIN_PASSWORD="${ADMIN_PASSWORD}" -n kube-system
 }
 
+vaultInstall() {
+  # Create namespace for Vault
+  kubectl create namespace vault
+
+  # Prompt user for Vault storage configuration
+  STORAGE_CLASS_NAME="vault-storage"
+  PV_NAME="vault-pv"
+  VOLUME_PATH="/data/volumes/vault"
+
+  # Create local storage class and persistent volume
+  createLocalStorageClassAndPV "$STORAGE_CLASS_NAME" "$PV_NAME" "$VOLUME_PATH"
+
+  # Add HashiCorp Helm repository
+  helm repo add hashicorp https://helm.releases.hashicorp.com
+  helm repo update
+
+  # Install Vault using Helm
+  helm install vault hashicorp/vault \
+    --namespace vault \
+    --set "server.ha.enabled=false" \
+    --set "server.dataStorage.enabled=true" \
+    --set "server.dataStorage.storageClass=$STORAGE_CLASS_NAME" \
+    --set "server.dataStorage.size=10Gi" \
+    --set "server.persistence.enabled=true" \
+    --set "server.persistence.storageClass=$STORAGE_CLASS_NAME" \
+    --set "server.persistence.size=10Gi" \
+    --values $MOUNT_PATH/kubernetes/install_k8s/vault/values.yaml
+
+  # Wait for Vault pods to be ready
+  echo "Waiting for Vault services to be up!!!!"
+  kubectl --timeout=120s wait --for=condition=Ready pods --all --namespace vault
+  if [[ $? -eq 0 ]]; then
+    echoSuccess "Vault services are now up!"
+  else
+    echoFailed "Vault services timed-out, please check!"
+  fi
+}
+
+vaultReset() {
+  # Uninstall Vault using Helm
+  helm uninstall vault -n vault
+
+  # Delete all PersistentVolumeClaims in the Vault namespace
+  kubectl delete pvc --all -n vault
+
+  # Clean up the local persistent volume and storage class
+  emptyLocalFsStorage "Vault" "vault-pv" "vault-storage" "/data/volumes/vault"
+
+  # Delete the Vault namespace
+  kubectl delete ns vault
+
+  # Provide feedback to the user
+  echo "Vault has been reset successfully!"
+}
+
 
 keycloakReset(){
   helm uninstall keycloak -n keycloak
@@ -2717,6 +2772,8 @@ function installCmd() {
     installLdap
   elif [ "$COMPONENT" == "dashboard" ]; then
     installDashboardwithCertManager
+  elif [ "$COMPONENT" == "vault" ]; then
+    vaultInstall
   elif [ "$COMPONENT" == "keycloak" ]; then
     installKeycloakWithCertMgr
   elif [ "$COMPONENT" == "ingress" ]; then
@@ -2794,6 +2851,8 @@ EOF
     dashboardReset
   elif [ "$COMPONENT" == "keycloak" ]; then
     keycloakReset
+  elif [ "$COMPONENT" == "vault" ]; then
+    vaultReset
   elif [ "$COMPONENT" == "ingress" ]; then
     ingressUnInst
   elif [ "$COMPONENT" == "ldap" ]; then
