Modified calico installation process

diff --git a/install_k8s/gok b/install_k8s/gok
--- a/install_k8s/gok
+++ b/install_k8s/gok
@@ -249,14 +249,23 @@ EOF
   mkdir -p "$HOME"/.kube
   sudo cp -i /etc/kubernetes/admin.conf "$HOME"/.kube/config
 
-  kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
-
   # shellcheck disable=SC2181
   if [ $? -ne 0 ]; then
     echo "Kubectl command execution failed, please check!!!!!"
     exit 1
   fi
 
+}
+
+calicoInst(){
+  helm repo add projectcalico https://projectcalico.docs.tigera.io/charts
+  kubectl create namespace tigera-operator
+  helm install calico projectcalico/tigera-operator --version v3.23.5 --namespace tigera-operator
+
+  if [ $? -ne 0 ]; then
+    echo "Calico installation failed, please check!!!!!"
+    exit 1
+  fi
 }
 
 helmInst() {
@@ -642,9 +651,10 @@ elif [ "$CMD" == "install" ]; then
     dockrInst
     haInst
     k8sInst
-    customDns
-    taintNode
     helmInst
+    taintNode
+    calicoInst
+    customDns
     cat <<EOF
 \______   |  |   ____ _____    ______ ____   __  _  ______  |___/  |_  _/ _______________  /_   |   _____ |__| ____
  |     ___|  | _/ __ \\__  \  /  ____/ __ \  \ \/ \/ \__  \ |  \   __\ \   __/  _ \_  __ \  |   |  /     \|  |/    \
