Redo documentation

diff --git a/install_k8s/util b/install_k8s/util
--- a/install_k8s/util
+++ b/install_k8s/util
@@ -64,6 +64,37 @@ desc(){
   kubectl describe $type "$name" -n $RELEASE_NAME
 }
 
+getHostIp(){
+  # Get the list of interfaces and their IP addresses
+  data=$(ip -br addr show | awk '{print $1, $3}')
+
+  # Print the list with index numbers
+  echo "$data" | awk '{printf "%d>>\t%s\n", NR, $0}'
+
+  # Ask the user to enter an index number
+  echo "Enter Index Number to view resource"
+  read INDEX
+
+  # Check if the entered index is a number
+  if ! [[ "$INDEX" =~ ^[0-9]+$ ]]; then
+    echo "Invalid index. Please enter a number."
+    return 1
+  fi
+
+  # Get the IP address corresponding to the entered index
+  ip=$(echo "$data" | awk "NR==$INDEX {print \$2}" | cut -d '/' -f 1)
+
+  # Check if an IP address was found
+  if [ -z "$ip" ]; then
+    echo "No IP address found for the entered index."
+    return 1
+  fi
+
+  # Print the selected IP address
+  echo $ip
+}
+
+
 logs(){
   data=$(kubectl get po -n $RELEASE_NAME 2>/dev/null | sed -e '1d' | awk '{printf "%d>>\t%s\n", NR, $0}')
   echo "$data"
